FROM python:3.12-slim AS builder

WORKDIR /app

RUN apt-get update && pip install poetry

COPY . /app

RUN poetry self add poetry-plugin-export
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /app/requirements.txt /app/
COPY --from=builder /app /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "employee.main:app", "--host", "0.0.0.0", "--port", "8000"]
